Support using private S3 buckets as remote mvn deployment targets
slipset/deps-deploy pull request #19
Opened 2020-11-04 15:35 UTC by RickMoynihan

Works via S3 wagon.

2020-11-06 07:41 UTC, slipset commented on src/deps_deploy/deps_deploy.clj
> +(aether/register-wagon-factory! "s3p" #(org.springframework.build.aws.maven.PrivateS3Wagon.))
I think I'd like for this to be `:imported` so we can say 
`((aether/register-wagon-factory! "s3p" #(PrivateS3Wagon.))`
Ditto for the following line.

2020-11-06 08:13 UTC, slipset requested changes
Unless there are reasons for not using `:import` I'd rather you imported the Wagon stuff

2020-11-06 09:22 UTC, RickMoynihan commented
Agreed.  Will try and update that later.

2020-11-16 15:44 UTC, RickMoynihan commented
I've pushed some changes to this.  Also I should probably add some docs to describe how to set this up.  I myself had made some mistakes in my local configuration that led me to assume it was doing one thing when instead it was doing another (picking up credentials via the AWS credential provider chain).

2020-11-23 18:17 UTC, slipset commented
Sorry for dropping the ball on this, but yes, please add some docs on this in the readme

2020-12-29 18:32 UTC, nnichols commented
Is there any way I could help w/ this? I'd love to be able to use this functionality

2020-12-29 19:38 UTC, slipset commented
I'll ping @RickMoynihan to see if he has some docs to add to the readme.

2021-01-04 08:30 UTC, RickMoynihan commented
Hi,

Sorry I've been off on paternity leave followed by xmas and new year, and now trying to catch up on everything that's happened at work etc.  I'll try and get round to this as soon as I can but no promises as to when.

2021-01-04 08:52 UTC, RickMoynihan commented
To briefly summarise what you need to do to use this, you just need to provide the credentials via the AWS provider chain.  Which more or less means either:

1. setting the env vars: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
2. providing them via java system properties `aws.accessKeyId` and `aws.secretKey`

or 

3. via an AWS credential profile, in the file `~/.aws/credentials` with the `AWS_PROIFLE` env var used to specify which profile to use (or the 'default' profile).

```
[default]
aws_access_key_id = AKIAXXXXX
aws_secret_access_key = SECRET_KEY
```

For more details see [s3-wagon-provider](https://github.com/s3-wagon-private/s3-wagon-private#aws-credential-providers) and if you need to know how to [configure an S3 bucket see here](https://github.com/s3-wagon-private/s3-wagon-private#aws-policy).

2021-01-04 19:11 UTC, merged